# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-18 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=30)),
                ('issue', models.CharField(max_length=20)),
                ('writer_artist', models.TextField(default='Please add names of writers and artists')),
                ('releaseDate', models.DateField()),
            ],
        ),
    ]
