# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listOfComics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('publisher', models.CharField(max_length=30)),
                ('issue', models.CharField(max_length=20)),
                ('writer_artist', models.TextField(default='Please add names of writers and artists')),
                ('releaseDate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Comics',
        ),
    ]
